require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'Firebase/Analytics'
platform :ios, '10.0'

target 'fairfoodie2' do
  config = use_native_modules!
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  
  use_react_native!(:path => config["reactNativePath"])

 

  target 'fairfoodie2Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'fairfoodie2-tvOS' do
  # Pods for fairfoodie2-tvOS

  target 'fairfoodie2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
